# Generated by Django 3.1.5 on 2021-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('B', 'Bought'), ('P', 'Pending'), ('NA', 'Not Available')], default='P', max_length=15),
        ),
    ]
